# Generated by Django 2.2.7 on 2020-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0002_remove_wheel_isdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=20)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
    ]
